import SwiftUI

struct SettingsView: View {
    @State private var credentials = CredentialsStore.shared
    @State private var debugLog = DebugLogStore.shared
    @State private var crashLog = CrashLogStore.shared
    @State private var externalLibrary = ExternalLibraryStore.shared
    @State private var isTesting = false
    @State private var testResult: String?
    @State private var testSucceeded = false
    @State private var rssFeedURLInput = ""
    @State private var isImportingFeed = false
    @State private var importResult: String?
    @State private var importSucceeded = false

    var body: some View {
        NavigationStack {
            Form {
                Section("Podimo credentials") {
                    TextField("Cookie", text: $credentials.cookie, axis: .vertical)
                        .lineLimit(3...6)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                    TextField("Authorization token", text: $credentials.authToken, axis: .vertical)
                        .lineLimit(2...4)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                }

                Section("Search") {
                    Picker("Region", selection: $credentials.searchRegion) {
                        Text("Netherlands (nl)").tag("nl")
                        Text("Spain (es)").tag("es")
                        Text("English (en)").tag("en")
                    }
                }

                Section {
                    Button {
                        Task { await testConnection() }
                    } label: {
                        HStack {
                            Text("Test Connection")
                            if isTesting { Spacer(); ProgressView() }
                        }
                    }
                    .disabled(isTesting || !credentials.hasCredentials)

                    if let testResult {
                        Label(testResult, systemImage: testSucceeded ? "checkmark.circle.fill" : "xmark.circle.fill")
                            .foregroundStyle(testSucceeded ? Color.podimoMint : Color.podimoCoral)
                            .font(.footnote)
                    }
                }

                Section {
                    Button("Clear credentials", role: .destructive) {
                        credentials.clear()
                        testResult = nil
                    }
                }

                Section("External Podcasts") {
                    TextField("RSS feed URL", text: $rssFeedURLInput)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .keyboardType(.URL)
                    Button {
                        Task { await importFeed() }
                    } label: {
                        HStack {
                            Text("Import Feed")
                            if isImportingFeed { Spacer(); ProgressView() }
                        }
                    }
                    .disabled(isImportingFeed || rssFeedURLInput.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)

                    if let importResult {
                        Label(importResult, systemImage: importSucceeded ? "checkmark.circle.fill" : "xmark.circle.fill")
                            .foregroundStyle(importSucceeded ? Color.podimoMint : Color.podimoCoral)
                            .font(.footnote)
                    }
                    Text("Add any podcast by its RSS feed URL — e.g. one generated by fetchrss.com — straight into your External library, no search needed.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }

                Section("Debugging") {
                    Toggle("Enable request logging", isOn: $debugLog.isEnabled)
                    NavigationLink("View Request Log") {
                        DebugLogView()
                    }
                    Text("Logs every GraphQL request and response, including headers and bodies, to help diagnose errors like a 404.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)

                    Toggle("Enable crash logging", isOn: $crashLog.isEnabled)
                    NavigationLink("View Crash Log") {
                        CrashLogView()
                    }
                    Text("Captures the stack trace from a crash and shows it here the next time you open the app.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }

                Section("About") {
                    Text("Paste the Cookie header and Authorization bearer token from an active open.podimo.com session. These are stored locally on this device and sent with every request.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
            }
            .navigationTitle("Settings")
        }
    }

    private func testConnection() async {
        isTesting = true
        do {
            _ = try await PodimoAPI.shared.getLibrary()
            testSucceeded = true
            testResult = "Connected successfully."
        } catch {
            testSucceeded = false
            testResult = error.localizedDescription
        }
        isTesting = false
    }

    /// Same destination as an "External" search result being followed from
    /// PodcastDetailView — fetching the feed once here both validates the URL
    /// and supplies the title/author/image an ExternalLibraryEntry needs.
    private func importFeed() async {
        let trimmed = rssFeedURLInput.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        if externalLibrary.isInLibrary(feedURL: trimmed) {
            importSucceeded = true
            importResult = "That feed is already in your External library."
            return
        }
        isImportingFeed = true
        importResult = nil
        do {
            let feed = try await ExternalPodcastAPI.shared.fetchEpisodes(feedURL: trimmed)
            let title = feed.title ?? URL(string: trimmed)?.host ?? "Untitled Podcast"
            externalLibrary.add(ExternalLibraryEntry(
                feedURL: trimmed,
                title: title,
                authorName: feed.author,
                description: feed.description,
                imageUrl: feed.imageUrl,
                addedDate: Date()
            ))
            importSucceeded = true
            importResult = "Added \u{201C}\(title)\u{201D} to your External library."
            rssFeedURLInput = ""
        } catch {
            importSucceeded = false
            importResult = error.localizedDescription
        }
        isImportingFeed = false
    }
}
